services:
  server:
    build:

      context: .
      dockerfile: Dockerfile

    ports:

      - '8421:8421'

    # volumes:

      # - ./server:/app

    environment:

      - APP_ENV=development
      - DATABASE_URL=sqlite:///./test.db
    
    # depends_on:

    #   - db

#   db:

#     image: postgres:14
#     environment:

#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: chat_db
    
#     volumes:
    
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: